version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs

build:
  os: ubuntu-24.04
  apt_packages:
    - cmake
  tools:
    python: "3.13"
    rust: "1.96" 
  jobs:
    pre_build:
      - cargo doc --document-private-items --no-deps --target-dir "./docs/source/_static/api/"
