[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "MNeuEventLib"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
  "numpy", 
  "matplotlib",
]

[project.optional-dependencies]
# Dependencies required to build the documentation.
docs = ["ipykernel", "nbsphinx"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "MNeuEventLib.core"
universal2 = true  # makes arm64 + x86_64 wheels for mac
