name:  

on:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt 
      - run: cargo fmt --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  linux: 
    name: Run unit tests
    needs: [lint, format]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --verbose
  
