name:  

on:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint and format (cargo)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

  linux: 
    name: Run unit tests (Linux) 
    needs: [lint]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --verbose
  
